services:
  - name: service1
    strategy: WeightedRoundRobin
    matcher: "/"
    replicas:
      - url: http://api:8081
        metadata:
          weight: 10
      - url: http://api2:8082
        metadata:
          weight: 5
