version: "3-8"

services:
  api:
    build: .
    command: ["./demo"]
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  api2:
    build: .
    command: ["./demo"]
    ports:
      - "8082:8081"
    environment:
      - PORT=8082

  load_balancer:
    build: .
    command: ["./main", "--config-path", "./example/config.yaml"]
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=./example/config.yaml
    depends_on:
      - api
